### ISSUE TITLE
Inner pages theming

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#1]
The work on the theme is mostly done, except for existing bugs on responsiveness and other visual annoyances that needs to be fixed. This task is about make a full sweep on a (migrated) site for find and polish them.

We already spotted these:

- [x] Style navigation portlet.
- [ ] Other required portlets.
- [x] The required fields are unstyled

Please feel free to add more items to the list as you find them.

**Comment by gforcada** [comment]
@sneridagh  how one is supposed to do that without a migrated Data.fs? Is it possible to share such a thing? Maybe not completely open but at least to the selected individuals that want to contribute to the project?

**Comment by sneridagh** [comment]
Umm you are right, the Data.fs on new.plone.org is not that big, only 130MB. The blobs are 500MB. It should be easy just to scp'ing them.

**Comment by sneridagh** [comment]
Fixed with Barceloneta in place now :)
