### ISSUE TITLE
Add search form Diazo rules

### ISSUE THREAD

**Issue by allcaps** [plone/ploneorg.core#102]
@cdw9: The search form is shown and hidden by JS. The form itself should be copied over by diazo. 
For the exact styling see the  theme.

What is the best practice???
a) Copy the Plone search form and fix the theme so the styling is like it supposed to be.
b) Write more complex Diazo rules so the theme html structure is respected.
c) Override the Plone search form template to reflect the theme html structure.
d) Something else.

#101

**Comment by RobZoneNet** [comment]
Done. I put in plone's search and made it look like the theme and act like it
