### ISSUE TITLE
Display premium sponsor logos on home

### ISSUE THREAD

**Issue by allcaps** [plone/ploneorg.core#103]
On the homepage just above the footer the *premium* sponsor logos are listed. 
I started a method in the homepage browser view. This has to be finished. I didn't look into the sponsor objects.

@cdw9 
#101

**Comment by sneridagh** [comment]
Done!

**Comment by tkimnguyen** [comment]
Actually we misunderstood when implementing... currently we are getting all sponsor logos. Need to fix that (so am reopening).

**Comment by tkimnguyen** [comment]
Fixed in https://github.com/plone/ploneorg.core/commit/ca570ce90872bfdc12ede9f9b3176f943d612406 and https://github.com/plone/ploneorg.core/commit/8f8360a2c11210b18be6c79f01e7b1eafa2dd9f1
