### ISSUE TITLE
Add organiser avatar to event items

### ISSUE THREAD

**Issue by allcaps** [plone/ploneorg.core#104]
In an effort to show the world there are people building Plone, we'd like to display the avatar of the event organiser. 

I guess this is needed:
- [ ] Add an related organiser field to the event ct.
- [ ] Use the reference to display the organiser avatar at the event.

I think we should respect the old organiser fields (or 'hide' them in a tab).

@cdw9 #101

**Comment by davisagli** [comment]
There may be multiple people organizing an event.

**Comment by allcaps** [comment]
Good point @davisagli. We need Plone.org to be released one day. I don't know if the current site accommodates this. If not, other stuff has priority.

Multiple is nice to have. For the person who is going to build this, some design guidance... I think multiple organizers should be displayed below the event text. Like this:

<img width="764" alt="screen shot 2015-11-23 at 22 45 30" src="https://cloud.githubusercontent.com/assets/1969342/11350866/fb3bc8e4-9233-11e5-8256-e6fc0052e343.png">

**Comment by sneridagh** [comment]
Finally decided that the event could have an image that is the one that should be shown, so we added a lead image behavior to the Event content type. It should be the logo of the sprint/event or the avatar of the organiser, etc
