### ISSUE TITLE
Display avatar when user is logged in

### ISSUE THREAD

**Issue by allcaps** [plone/ploneorg.core#107]
The header needs to display the current users avatar. Once clicked a [dropdown](http://getbootstrap.com/components/#dropdowns) should be displayed containing at least:

 - Signed in as ``[username]`` (no link)
 - Your profile
 - Submit event
 - ... ?
 - Sign out

**Comment by jensens** [comment]
We use Github OAuth2 as login provider and so we do not have an local avatar image, so the default Plone portrait mechanism does not work.

But Authomatics User class offers a picture URL, if the OAuth2 provider sends one. Github does (see http://peterhudec.github.io/authomatic/reference/providers.html#authomatic.providers.oauth2.GitHub)

in pas.plugins.authomatic you can map the ``picture`` url to a property on the user property sheet:

        "propertymap": {
            ...
            "picture": "avatar_url"
            ...
        },

The simply access the ``avatar_url`` of users propertysheet and use it in some img tag.

**Comment by sneridagh** [comment]
Done!
