### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#11]
We will only migrate the essential from the old plone.org. Basically all the Foundation information.

Some job has been done on this:

* New Dexterity content type for Plone Foundation Member.
* Successful initial migration tests from a devdrop of the real plone.org.

Needs to be done:
- [x] Finish and test more on migrations.
- [x] Publish that tests into the development server for the people to check for them.
- [x] Migrate p.a.vulnerabilities content

**Comment by gforcada** [comment]
@sneridagh what's specifically missing on the migration? How one can jump and help on that?

**Comment by sneridagh** [comment]
@gforcada I think that the only thing to be done is to check if the migration was correctly and nothing is missed. This week noticed that the content from the p.a.vulnerabilities should be also migrated, we should look into it.

**Comment by sneridagh** [comment]
@gforcada Did we finally decided that the migration of the remaining items (p.a.vulnerabilities) is going to  be done by zexp it? If so, then we should be ready to close this one as soon as someone review a working migration just in case I've missed something or there is something wrong with it.

**Comment by sneridagh** [comment]
The migration was tested and initially checked successfully in new.plone.org. Only the migration on p.a.vulnerabilities is needed to be done.

**Comment by sneridagh** [comment]
Done Done Done Done :)
