### ISSUE TITLE
Deploy the stats retriever on production server

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#118]
We need to deploy the stats retriever on the production server. Gil was the last that worked on it and probably knows what's required to achieve it.

**Comment by gforcada** [comment]
@smcmahon I have ssh access to the server, so my question is: I need to create a local file (not to be put on any VCS whatsoever) full of credentials and passwords.

May I put the file right there or that needs to be instrumented somehow?

The same goes with the cronjob that needs to call ``bin/update_contributions``, may I just do ``crontab -e`` and add stuff or there's some ansible playbook where I should add those things in?

**Comment by fulv** [comment]
@gforcada If you send me the file, I can include it and the cron job in the ansible deployment, and then document how to do it for others.

**Comment by gforcada** [comment]
@fulv ok, I will try to put everything together and ping you for it

**Comment by gforcada** [comment]
@fulv the configuration file is on the server on ``/home/gforcada/contributors.cfg``, be sure to keep it always safe as it's full of credentials :-)

The cronjob should be something like this:
``./bin/update_contributors --config contributors.cfg``

Run it once per day, no idea what would be the best time given the globally distributed nature of Plone...

**Comment by gforcada** [comment]
@fulv if you want to try it first do something like this:

``./bin/update_contributors --config contributors.cfg --debug --debug-limit 10 --fetch-only --fetch-specific community`` <--  does not require the plone instance at all

``./bin/update_contributors --config contributors.cfg --debug --debug-limit 10 --fetch-only --fetch-specific issues`` <-- uses github auth API

``./bin/update_contributors --config contributors.cfg --debug --debug-limit 10 --fetch-only --fetch-specific stackoverflow`` <-- needs plone instance with some users having a stackoverflow URL

**Comment by sneridagh** [comment]
Done!
