### ISSUE TITLE
Badges system for the contributors

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#12]
We need a system that based on the group membership of the users, assign to the contributors profile page the related "badges", like "framework team" or "release manager". This relates to #20. The system should be done using c.workspaces. It should be easy to assing new members to the default teams and it should be connected with the contributor profile page.

- [ ] Do the actual system
- [ ] Do the badges in CSS for simple placement in the views

**Comment by 3dogMcNeill** [comment]
added Rob to #20 for CSS badges

**Comment by allcaps** [comment]
The badges are in ploneorg.theme repo. They are in SVG and EPS format. The SVG for embed in the site (works for IE9+).
