### ISSUE TITLE
Past Events View Needs Styling

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/ploneorg.core#120]
http://barcelona_direct.plone.org/events/aggregator/event_listing?mode=past

![pastevents](https://cloud.githubusercontent.com/assets/7101218/13014022/e01224ec-d17f-11e5-8bbb-6c8a38af91e6.png)

**Comment by polyester** [comment]
this seems to be an issue with plone5.0.4 css not getting correctly applied. It works with earlier and later versions, we will fix it this week.

**Comment by polyester** [comment]
found it, there is a faulty plone-legacy-compiled.css in the version of Products.CMFPlone that we use. Switching it for the current one (5.0 or 5.1 branch) fixes this. We'll probably hand-do this until 5.0.5 comes out.
