### ISSUE TITLE
missing redirects

### ISSUE THREAD

**Issue by djay** [plone/ploneorg.core#131]
Seems a lot of important urls aren't getting redirected to their new locations which is a shame. Will will lose link juice because of this.

E.g. download link at the bottom of https://plone.com/try-plone/try-plone/#downloading

Perhaps someone with access to analytics can look at the top 404s?

**Comment by 3dogMcNeill** [comment]
Tracking.

**Comment by jensens** [comment]
plone supports redirections using the redirectiontool - so please just add them. this is so important!

**Comment by tkimnguyen** [comment]
We can also include a message (temporarily) about looking at old.plone.org on the 404 page

**Comment by 3dogMcNeill** [comment]
Here's the link to 404 pages report for 8-12 May

ht[tps://docs.google.com/spreadsheets/d/1kzZ1Qcq10pIYAQaTxuStHsbXuAud0Aq_LI4SRPHFsfw/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1kzZ1Qcq10pIYAQaTxuStHsbXuAud0Aq_LI4SRPHFsfw/edit?usp=sharing)

**Comment by rioksane** [comment]
I wonder if this issue is still relevant after 5 years?

**Comment by jensens** [comment]
Not relevant at all anymore - given all links on `*.plone.*` have been checked already. Btw. do we run some kind of link-checker regularly to avoid this kind of problems?

**Comment by rioksane** [comment]
OK, thanks for clarification @jensens! As far as I know, we don't run link checkers regularly. But we are working on plone.org content improvements right now on the marketing team so we're going through the site section by section. I'll close this issue.
