### ISSUE TITLE
fix the site title

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#138]
for some reason the title of the front page of the site still shows up as "Plone CMS: Open Source Content Management — Site" even though we changed the site title to "Plone.org" in the Site panel

**Comment by rioksane** [comment]
This doesn't seem to be an issue anymore. I'll close this. 

Site setting says "Plone: Enterprise Level CMS - Free and OpenSource - Community Driven - Secure"
Homepage title is "Plone CMS: Open Source Content Management"
