### ISSUE TITLE
Update content on commuity/documentation

### ISSUE THREAD

**Issue by svx** [plone/ploneorg.core#144]
I tried myself to do that, but it seems I do not have permissions to do so, the content on https://plone.org/community/documentation/documentation could/should be improved :) .

- replace link to old mailing list with link to the section n community.plone.org
- replace link to old issue tracker on dev.plone.org with link to GitHub one, with a link/sentence to/about http://docs.plone.org/about/contributing.html

**Comment by polyester** [comment]
I've given you permission on the whole /community/documentation folder, you should be able to edit now

**Comment by svx** [comment]
Thanks ! done !
