### ISSUE TITLE
Green .btn-secondary buttons too dull on the front page

### ISSUE THREAD

**Issue by pigeonflight** [plone/ploneorg.core#148]
## Before
The shade of green for the buttons on the frontpage (.btn-secondary) is too dull. 
![green-before](https://cloud.githubusercontent.com/assets/31827/15237826/8271c09a-1897-11e6-929e-7e6fca209635.png)
## After
By borrowing the shade from the .navbar-default class and adjusting it to a green hue plus a bit of desaturation.... we can get a green that aligns more with the general hues of the theme (#2DA067).
![green-after](https://cloud.githubusercontent.com/assets/31827/15237937/611f88e0-1898-11e6-893b-8f3fe74ac8ff.png)

**Comment by tkimnguyen** [comment]
Agree the current green is hard to see, but @RobZoneNet and I maintained a light touch as we altered the theme styles only as much as necessary for accessibility compliance. We Are Not Themers ™ and we did not want to tread on @allcaps 's design.

**Comment by vikas-parashar** [comment]
I also gave it a try. 

![plone2](https://cloud.githubusercontent.com/assets/5694967/15261611/40ba7d56-197b-11e6-9458-936f63494739.png)


Also, goes with the theme
 ![plone](https://cloud.githubusercontent.com/assets/5694967/15261468/5ada7e76-197a-11e6-9b3e-1735dee750f3.png)

**Comment by pigeonflight** [comment]
I'm good with @vikas-parashar's version too.

**Comment by allcaps** [comment]
Go with @vikas-parashar color.

**Comment by polyester** [comment]
done with https://github.com/plone/ploneorg.theme/commit/6b5cb3b8de0fa40009c4dca6c85bf2763b55643a (still needs deploying on the live server)

**Comment by tkimnguyen** [comment]
@polyester pulled and clients restarted but am not seeing the colour change...

**Comment by polyester** [comment]
probably a caching issue, the 'security' megatron which was in the same update is showing.
