### ISSUE TITLE
Where to store content types schema?

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#15]
As I type there are 3 content types right now:
- contributor.xml: with ``model_source`` filled with XML (really hard to read as is using ``&lt;`` and ``&gt;``
- FoundationMember.xml:  with ``schema`` pointing to a python class interface
- homepage.xml: same as FoundationMember

So which approach is the way forward? I would say python? And specially embedding an xml inside another xml, that's really hard to maintain...

**Comment by gforcada** [comment]
@sneridagh I see that ``profiles/default/types/contributor.xml`` is not even registered on ``profiles/default/types.xml``.

I see that @MatthewWilkes created it, what's the purpose of this content type?

**Comment by MatthewWilkes** [comment]
It was part of an effort a few years ago to wrap up metadata about contributions into a unified profile for community members. You can feel free to delete it.

Personally, I'd say that the others have the right idea, the contributor one is just like that because of the portal_setup exporter.

**Comment by sneridagh** [comment]
I left it just in case... We can get rid of it.

**Comment by gforcada** [comment]
Done!
