### ISSUE TITLE
error opening https://plone.org/edu

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#151]
For some reason I can't open https://plone.org/community/edu/about-ploneedu (I see it in https://plone.org/community/edu/folder_contents). Mysterious since I'm sure I'm the one who copied this page over two weeks ago (but left it private).

**Comment by polyester** [comment]
it gives me ERR_TOO_MANY_REDIRECTS, so a clear indication the nginx rewrites are doing the wrong thing.

**Comment by polyester** [comment]
ah, already see it. nginx rewrites are RegEx. So we might want to say ^/edu instead of /edu, if you want to **only** catch plone.org/edu, but not plone.org/community/edu

(same goes for the other rewrites in there)

**Comment by tkimnguyen** [comment]
I've fixed temporarily on the server, adding ^ in front of /edu and /help, and will make those changes in the playbook once I have access

**Comment by tkimnguyen** [comment]
Included the regexps changes to the ansible playbook plone-org branch
