### ISSUE TITLE
sprints content type

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#16]
I'm about to start writing the sprints content type, on top of my head I kind of think that it should be:
- folderish: so we can put images, report pages and what not inside
- as for fields:
  - name of the sprint
  - where it takes place (with geolocation?)
  - how many days (p.a.event?)
  - organizer(s) (FoundationMember users?)
  - free form description of the event
  - travel information
  - venue
  - leading image
  - topics of the sprint (keywords so that can be used to generate reports and search for them?)

Then a "I'm sprinting" button will allow to add oneself to that sprint. A browser view will create a relation between the Member and the sprint.

Anything else?

**Comment by 3dogMcNeill** [comment]
work on comment #1 first, comment#2 after

**Comment by gforcada** [comment]
I guess we are not planning on adding this, right? 🤔
