### ISSUE TITLE
search results page is broken

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#160]
If I search for a term using the search field, I'm taken to the search results page but once I'm on that page I can't update the search term to look for and the page keeps auto refreshing, e.g. https://plone.org/@@search?SearchableText=

**Comment by polyester** [comment]
cannot reproduce, works fine for me in two browsers.

**Comment by tkimnguyen** [comment]
Dangit. It was happening to me yesterday, but just tried 3 browsers now and not seeing it. Thx :)
