### ISSUE TITLE
Cut-n-paste bug on sponsor page

### ISSUE THREAD

**Issue by tmog** [plone/ploneorg.core#163]
"Large firms (1 or 2 full time employees)" on https://plone.org/sponsors/become-a-sponsor

![skaermbillede 2016-05-24 kl 16 22 49](https://cloud.githubusercontent.com/assets/823925/15507468/070a550a-21cc-11e6-8206-fca9b2ff064f.png)

**Comment by tkimnguyen** [comment]
thx @tmog !!! fixing now :)

**Comment by tkimnguyen** [comment]
Fixed!
