### ISSUE TITLE
Possible misleading link description

### ISSUE THREAD

**Issue by svx** [plone/ploneorg.core#166]
On https://plone.org/get-started we have: 

![wrong_description-plone-download](https://cloud.githubusercontent.com/assets/358860/15530668/147ec128-2256-11e6-9bef-0c0e2df66182.png)

For me the link description is misleadiing, I expect here instructions as the link says, I got confused when the link directed me to a download page

**Comment by tkimnguyen** [comment]
I think https://plone.org/get-started could also do with info on where you can get a hosted Plone ...

**Comment by tkimnguyen** [comment]
@svx what would you recommend that description text be?

**Comment by djay** [comment]
+1 @tkimnguyen

**Comment by svx** [comment]
This is fixed with: https://github.com/plone/ploneorg.theme/pull/7

Thanks !
