### ISSUE TITLE
tests?

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#17]
Tests are failing because there are only tests for a content type that does not exist, but there is still some code about it around (add-on content type).

Should we get rid of those tests and start creating tests for what we do?

**Comment by gforcada** [comment]
@sneridagh what's the idea here, should we add tests at all?

**Comment by sneridagh** [comment]
Yeah, we barely had a look at them until now. We should have at least the more basic ones.

**Comment by gforcada** [comment]
I added the most basic one:  https://github.com/plone/ploneorg.core/commit/a2d0c6cdd3ac64afb14144b9fc82a72e8e8ecfd7

I will try to add more later on.
