### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by vikas-parashar** [plone/ploneorg.core#173]
Here: https://plone.org/foundation/copyright-licensing-logo/archives/the-plone-logo

![image](https://cloud.githubusercontent.com/assets/5694967/15619915/cd27c57e-2474-11e6-9c5b-8980b22a6c3a.png)
Image url is https://plone.org/foundation/copyright-licensing-logo/archives/plone-logo-128-white-bg.png
which is redirecting to https://plone.org/authomatic-handler/

**Comment by tkimnguyen** [comment]
There must be some old workflow state leftovers. In the old.plone.org images and files had a workflow state. Had to download the image and re-add it to the folder and relink from the referring page. Thanks for catching that, @vikas-parashar!
