### ISSUE TITLE
Missing byline in plone.org content

### ISSUE THREAD

**Issue by hvelarde** [plone/ploneorg.core#175]
This is important for context; take for instance this news item: https://plone.org/news/2016/plone-foundation-announces-three-new-members-2016

When it was published? When it was modified?

**Comment by djay** [comment]
Thats a plone.org theme issue.

**Comment by vikas-parashar** [comment]
related https://github.com/plone/ploneorg.core/issues/95

**Comment by hvelarde** [comment]
@djay one more time: [metadata](https://en.wikipedia.org/wiki/Metadata) is "data that provides information about other data"; metadata is content, metadata is not theme.

this is indeed duplicated.
