### ISSUE TITLE
No way to edit location

### ISSUE THREAD

**Issue by hvelarde** [plone/ploneorg.core#179]
After login with GitHub there's no way to edit location displayed in the profile.

**Comment by tkimnguyen** [comment]
I think you have to edit what shows up in your Github profile; that's what's displayed on your Plone.org profile.

**Comment by hvelarde** [comment]
that's not the case:

* GitHub: https://github.com/hvelarde
* plone.org: https://plone.org/profile/hvelarde

**Comment by tkimnguyen** [comment]
Related to the Github script issue https://github.com/plone/ploneorg.core/issues/180 ?

**Comment by gforcada** [comment]
I think the problem here is that once the data is only fetched at registration time, not at every login. So the bug report should go to the pas plugin, whatever the name is.

**Comment by tkimnguyen** [comment]
That would be https://github.com/collective/pas.plugins.authomatic

**Comment by jensens** [comment]
fixed in the plugin.

**Comment by hvelarde** [comment]
it may be fixed in the plugin, but is not in production yet.

**Comment by jensens** [comment]
@hvelarde thats outside my sphere

**Comment by tkimnguyen** [comment]
@hvelarde you're harsh :) Will try to get it deployed this morning!

**Comment by tkimnguyen** [comment]
Deployed and clients restarted. Logging into plone.org (still) works :) I changed my github profile location and logged out of then logged back into plone.org but the site does not seem to have pulled in my changed location info from github.

**Comment by jensens** [comment]
hmm, this was supposed to work, need to look whats going on.

**Comment by jensens** [comment]
Ok, found, propertysheet was cached for good reasons.

**Comment by tkimnguyen** [comment]
@hvelarde is it working for you? OK to close?

**Comment by tkimnguyen** [comment]
Works nicely for me. Closing but @hvelarde please reopen if necessary. Thanks @jensens !

**Comment by hvelarde** [comment]
thanks, guys!
