### ISSUE TITLE
Design for Mozilla-like page for "New to Plone" section

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#18]
This will be the "sub-homepage" for showing guidance to the newcomers to Plone. The idea for it is to have a page similar in structure and content as: https://www.mozilla.org/en-US/contribute/signup/

We need mockups and the actual implementation of the page/template.

UPDATE 8/3/15: I've turned this into a design only issue and created a new one for the content.

**Comment by gforcada** [comment]
For reference the mozilla page is this one: https://www.mozilla.org/en-US/contribute/signup/

**Comment by 3dogMcNeill** [comment]
needed: mockups, icons, and content (contribution buckets: align with teams)

**Comment by 3dogMcNeill** [comment]
Can the following be nicely (aka not visually confusing) integrated:
* Plone Docs
* Stackoverflow
* Chat
* Local Users Groups

**Comment by allcaps** [comment]
I won't spint on this. Other things have priority now. Can pick it up later though.

**Comment by allcaps** [comment]
@sneridagh and @3dogMcNeill, what is the primary goal of this page? 

https://www.mozilla.org/en-US/contribute/signup/ is signup focused but during the conference I got the impression that the page should be a 'Getting started' or 'New to Plone' page. Eg links to:
- Install Plone
- Beginners tutorial
- Documentation
- Community help

Is the Plone contributor agreement part of the signup process?

**Comment by 3dogMcNeill** [comment]
@allcaps great questions, glad you asked. We have a Marketing/Communications Team meeting Friday, Oct 30. I put this on the agenda. Unfortunately the meeting is after our plone.org meeting but I'll update you afterward.

**Comment by 3dogMcNeill** [comment]
@allcaps everyone is agreed on having 2 landing pages. 

1. New to Plone landing page with:
 - Install Plone
 - Beginners tutorial
 - Documentation
 - Community help
 - Local Users Groups
 - include report a bug? (direct to github)
 - report documentation fixes (have to talk to Sven, this may be post-launch addition)

2. Plone Community landing page with:
 - Plone teams and description
 - how to join teams and/or contribute to Plone

I can write up the text for these pages but let me know how you want to proceed. Maybe we can discuss in email?

**Comment by allcaps** [comment]
Nice list. I’ll start a design and send it via email.

**Comment by allcaps** [comment]
The design lives in the pdf on the shared drive and the html / css is added to ploneorg.theme.
