### ISSUE TITLE
Links in doormat

### ISSUE THREAD

**Issue by loechel** [plone/ploneorg.core#183]
following links in the doormat have no target:

- Stay up to date
- Downloads

Missing Shortcuts:
- "Security" start Page is missing

**Comment by tkimnguyen** [comment]
@loechel what do you suggest for the Security start page?

**Comment by loechel** [comment]
@tkimnguyen well "Stay up to date" should eighter not be a clickable link or it should bring you to an overview of different communication channels with a more prominent calll to action to subscribe the announcements or marketing mailing lists. 

If we do talk a loot about security, we should have a link to our security section in the doormat, beside the "check hotfixes" maybe under Support or Documentation that give them the overview of our security concepts. --> Well we have to bring them up to date before!

**Comment by loechel** [comment]
fixed and deployed
