### ISSUE TITLE
Live search box misaligned.

### ISSUE THREAD

**Issue by vikas-parashar** [plone/ploneorg.core#185]
Live search box is misaligned in Chrome 51, Opera Developer 39, Vivaldi browser but aligned properly in Firefox 46 on Ubuntu 14.04

![image](https://cloud.githubusercontent.com/assets/5694967/16170951/db2eb8c2-3580-11e6-805e-872224dcc358.png)

**Comment by rioksane** [comment]
<img width="633" alt="Screenshot 2021-01-17 at 16 56 24" src="https://user-images.githubusercontent.com/5127672/104846797-046dec80-58e5-11eb-9d91-5345a33cba22.png">
The alignment seems to be quite ok for now. Firefox 84 (osx) and Chrome 87 (osx). 

I'll close this,
