### ISSUE TITLE
Plone's addons-controlpanel points to missing page

### ISSUE THREAD

**Issue by pbauer** [plone/ploneorg.core#195]
The Addons-controlpanel of Plone (/prefs_install_products_form) points to http://plone.org/documentation/kb/installing-add-ons-quick-how-to which now only lives on http://old.plone.org/documentation/kb/installing-add-ons-quick-how-to

Can we add a redirect from http://plone.org/documentation/kb/installing-add-ons-quick-how-to to http://docs.plone.org/manage/installing/installing_addons.html wchih seems more up-to-date than the one on old.plone.org?

See https://github.com/plone/Products.CMFPlone/issues/1690

**Comment by tkimnguyen** [comment]
The redirect from ^/documentation/kb/installing-add-ons-quick-how-to to http://docs.plone.org/manage/installing/installing_addons.html was in place as of Sept. 6. https://github.com/plone/ansible-playbook/blob/plone-org/local-configure.yml#L150
