### ISSUE TITLE
https://plone.org/upgrade does not exist

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#199]
And is linked from the `@@plone-upgrade` https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/templates/plone-upgrade.pt#L46

Was that migrated somewhere else?

**Comment by polyester** [comment]
It was not migrated to the new plone.org, but instead was cleaned up and migrated already a long time ago to http://docs.plone.org/manage/upgrading

so probably the better solution is to change the @@plone-upgrade template above to point to that

**Comment by gforcada** [comment]
That's a good idea, but also adding a redirect on nginx (or whatever) is in front of plone.org to redirect /upgrade there.

**Comment by gforcada** [comment]
Reopening as the redirect is still not in place...

**Comment by gforcada** [comment]
Now it is in place. Thanks @tkimnguyen !

**Comment by tkimnguyen** [comment]
I created a Link but I see that the Ansible playbook has a number of nginx redirects... I guess I will convert this link to a redirect. 

Sorry, I will try to go through and address more of these ploneorg.core issues!

**Comment by tkimnguyen** [comment]
OK I've added the redirects for the two plone.org Link objects: /upgrade and /donate and will run the playbook.

**Comment by tkimnguyen** [comment]
Everything works! Deleted the Link objects.

**Comment by mauritsvanrees** [comment]
Thank you!
