### ISSUE TITLE
Design the badges, assign them to teams

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#20]
Sally's post:
http://blog.jazkarta.com/2015/01/30/how-to-create-a-badge-system-in-plone/

can help. I've seen that c.roster maybe it's not needed at all. It can be done using c.workspace solely.

**Comment by 3dogMcNeill** [comment]
what do we need in addition to the badges in the Google doc? https://drive.google.com/a/iskra.cat/file/d/0BzKEPxDtlwSzbVJsdXFmeW1IZ1k/view?usp=sharing

**Comment by sneridagh** [comment]
If everybody is ok with the original design, then we can transform them on a pure CSS component (this was the original Albert's idea) or transform them to usable images (less work).

**Comment by 3dogMcNeill** [comment]
I'm ok with the original design. I'll find out if Rob is interested in doing them in CSS.

**Comment by 3dogMcNeill** [comment]
Start with team badges for launch. Gil to create list of future badges to add to collection, ex. sprints

**Comment by polyester** [comment]
I'd like the badges to be slightly changed:

- remove "Plone" from as many of them as possible. It gets redundant rather quickly... "Security team" should do, no need to have "Plone Security Team", Plone this, Plone that. We're on plone.org, after all. *Maybe* only needed for Foundation, although I would even leave it off there.

- 'marqueting' may be charmingly french, but is not entirely correct.

I can see if I can open the AI files, although that can be temperamentful on my Inkscape.

**Comment by 3dogMcNeill** [comment]
made a .PNG so everybody can view the badges. Personally, I prefer the version in this file vs. the badges on the mock up Contributor profile https://drive.google.com/file/d/0BxSbB3YjvNhsanY0RjdpU3JBdEE/view?usp=sharing

**Comment by tkimnguyen** [comment]
For sponsorship badges: premium sponsor, sponsor, Foundation Hero (individual), university sponsor, non-profit org sponsor, government sponsor

**Comment by tkimnguyen** [comment]
Sorry if I missed this discussion or if it doesn't fit in this ticket.

To go with team member badges, could we also have badges for community roles, e.g. conference organizer, sprint organizer, symposium organizer, team leader?

**Comment by allcaps** [comment]
FYI the SVGs are currently in: ploneorg.core/src/ploneorg.theme/ploneorg/theme/diazo_resources/img/badges

**Comment by sneridagh** [comment]
I'm closing this to create a new issue for the whole c.workspace and c.badges implementation.
