### ISSUE TITLE
Mention ansible kit

### ISSUE THREAD

**Issue by svx** [plone/ploneorg.core#207]
I was not able to find it on current plone.org site, we had that on the old plone.org, would be nice to have it back on the current one.

**Comment by rioksane** [comment]
@svx going through these old issues. Is this still valid? If it is how and where would you like to mention ansible kit? Old plone.org is not available anymore for reference.

**Comment by fulv** [comment]
I think every release page mentions the ansible kit:
https://plone.org/download/releases/5.2.4

The only place I could find that might need a sentence and a link is
https://plone.org/download/download

**Comment by rioksane** [comment]
Added a mention and link about ansible kit here https://plone.org/download/download
