### ISSUE TITLE
Design contributor profile and badge listing

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#21]
We need to redesign the contributor profile page, we want it to be more weighted and redistribute content too. We need to show the already in place new contributor stats. See comments.

**Comment by 3dogMcNeill** [comment]
Designer needed.

**Comment by 3dogMcNeill** [comment]
S. to help with design. 
![contributor](https://cloud.githubusercontent.com/assets/7101218/8035434/b29849b8-0dbe-11e5-883d-7b1e2498a3e0.png)

**Comment by allcaps** [comment]
Design and create html/css for the profile page.
We also need a badge listing.

@skleinfeldt wrote: ... badge metadata and view template roughly like the Mountaineers: https://www.mountaineers.org/membership/badges/conservation-stewardship-badges/copy_of_fire-lookout-crew-leader with a body description and a "how do I get this badge" section.

There is a little start here:
https://github.com/plone/ploneorg.theme/blob/allcaps-theme/ploneorg/theme/diazo_resources/profile.html

**Comment by sneridagh** [comment]
This is what it looks like now. The badges is somewhat we don't know yet how to present them. @allcaps @3dogMcNeill @polyester @albertcasado @RobZoneNet @tkimnguyen @skleinfeldt @esteele Any suggestions are welcome!

@RobZoneNet is currently working on improving the facts boxes and the icons.

![screen shot 2016-04-27 at 20 58 47](https://cloud.githubusercontent.com/assets/486927/14864602/e765ecbc-0cba-11e6-8dc5-015cb0198587.png)

**Comment by tkimnguyen** [comment]
That looks good

**Comment by sneridagh** [comment]
Working and in place.
