### ISSUE TITLE
fix lead image in front page event blocks

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#210]
On the front page of plone.org in the events area, the lead images of events are funny looking
 
![untitled 2](https://cloud.githubusercontent.com/assets/815418/20804386/4f0608ea-b7b8-11e6-9d4f-4c3626f26420.png)

**Comment by rioksane** [comment]
I think someone has fixed this. The images look ok now? Or they just happen to be in the right aspect ratio in the latest  events. I think this is something that the marketing team can monitor until new plone.org theme is available

**Comment by rioksane** [comment]
I will close this issue. The marketing team has agreed on how to input lead images on events and news and will monitor them regularly. 

Also, the upcoming plone.org renewal will make this issue obsolete, hopefully.
