### ISSUE TITLE
Plone 5.0.x default home page links are broken

### ISSUE THREAD

**Issue by mpommrehn** [plone/ploneorg.core#211]
The links to "available themes from plone.org" and "available add-ons" on the built-in default home page in a fresh Plone install both go to https://plone.org/products and get a message "that page does not seem to exist"

Also, we really need some more stock 5.0-compatible themes, please.
Thanks

**Comment by tkimnguyen** [comment]
thx @mpommrehn - there are some very nice new P5 themes; see https://community.plone.org/t/successful-google-summer-of-code-2016-projects/3104 and we are thinking of ways to highlight themes on plone.org (as well as a better add-on listing, which is in the works).

**Comment by mpommrehn** [comment]
Thanks very much, T. Kim!

Those themes look very nice!  Will try a couple.

Highlighting them on Plone.org<http://Plone.org> would be great.

I'm new to Plone and CMSs, so am grateful for the guidance. I picked Plone for its excellent security, and had a good experience installing it on Azure and my Mac using Bitnami.  I'm liking Plone a lot!  Great work!  Thanks!

FYI it looks like the Plone Theme demo server is not responding.  It happens on multiple demo links in the README.rst files in the various theme pages.

Example for the Spot theme:
http://107.170.136.197:8080/spot

Best,

Mark

Mark Pommrehn
mark.r.pommrehn@outlook.com<mailto:mark.r.pommrehn@outlook.com>

On Dec 15, 2016, at 14:01, T. Kim Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


thx @mpommrehn<https://github.com/mpommrehn> - there are some very nice new P5 themes; see https://community.plone.org/t/successful-google-summer-of-code-2016-projects/3104 and we are thinking of ways to highlight themes on plone.org<http://plone.org> (as well as a better add-on listing, which is in the works).

-

**Comment by tkimnguyen** [comment]
@mpommrehn so glad to hear you're liking Plone! Yeah I removed the demo theme server URL from one of the new theme repos and will do the rest now.

**Comment by tkimnguyen** [comment]
https://plone.org/products now redirects to https://plone.org/download. Closing this and will open issues to remove the demo server theme URLs from the readmes.

**Comment by tkimnguyen** [comment]
@mpommrehn have a look at https://plone.org/download now... it highlights these five new themes

**Comment by mpommrehn** [comment]
@T. KIm, That’s great. They will be easy for people to find now.  Thanks!
I installed Clean Blog and like it a lot.  Glad for the contributions of Google Summer of Code!

On Dec 17, 2016, at 12:12 AM, T. Kim Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


@mpommrehn<https://github.com/mpommrehn> have a look at https://plone.org/download now... it highlights these five new themes

**Comment by tkimnguyen** [comment]
@vikas-parashar did a great job!
