### ISSUE TITLE
Quallity Control of postings

### ISSUE THREAD

**Issue by svx** [plone/ploneorg.core#212]
plone.org is some kind of a business card of Plone, and so should be the content and also how the content looks like, if a posing is looking not that nice this is bad for marketing and so for Plone ...

Looking at this is one example:
![po-cq](https://cloud.githubusercontent.com/assets/358860/21292193/5bb5e866-c4fc-11e6-99ee-e207abd1c5fe.png)

I am really thankful for people who actually using plone.org, but please would you mind to take the extra two minutes and take care that the pictures all have the same dimensions ? It would like way more professional that this different sizes ....

Yeah I know lots of people do not care about stuff like this, but I do and IMHO it is important, if you claim that you are a Enterprise grade CMS that we also should show that in our own content and postings.

Thanks !

**Comment by tkimnguyen** [comment]
@svx I don't know how to respond to this sort of criticism, other than to say that I got the news item out, it was well written, I included photos, it got a lot of views on Twitter and Facebook. It may not be perfect, but it was better than not having the news item. As for professionalism, I am a professional, and am unpaid, so really please refrain from these unproductive attacks and stop energy.

**Comment by svx** [comment]
@tkimnguyen like I said I am really thankful that you do all this and I am sorry and I apologize how I said this, you are right this was not my finest moment.

I am sorry !!

But still I stand to my base point, which is we should try to make content and postings look according to the our product.
In the example from above that would mean we take care that all the included pictures are the same size, this would look way better.
It is not always about the content as in written words, or how many views or like I get, it is also about how I present a product visual.
That  are often the 'little small things' which make you stand out of the bog blurb of others.

BTW: *views* or *likes* are really relative, since lots of people you know like your stuff :) IMHO I do not target these as audience I would go for potential new use and for these these small things matter more than they do for your *usual crowd*

And I am sorry that you are unpaid for all this, but guess what so I am, too :)

**Comment by tkimnguyen** [comment]
Thanks @svx 

I will try to get matching photo sizes. Asking for that, without the added commentary, would have accomplished what you wanted.

**Comment by tkimnguyen** [comment]
![screen shot 2016-12-18 at dec 18 10 40 27 am](https://cloud.githubusercontent.com/assets/815418/21294917/80723378-c50e-11e6-8440-b2e26c0d9c80.jpg)

**Comment by svx** [comment]
Thank you !! And sorry again !
