### ISSUE TITLE
Contextualize old content

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#213]
Take a look at https://plone.org/news/old-news/new-documentation-area.
Apart from the broken links, without a temporal reference the amount of misleading information on that page is staggering.

#95 would go a **long** way toward setting the proper expectations for the reader.

But I wonder if there shouldn't be some way for providing ad-hoc up to date information.  A manual process is probably unsustainable, e.g. adding a static text portlet.  Instead, perhaps we could add an info box that tries to be smart with some fixed rules.  For example, if a page refers to *documentation*, or links to old documentation URLs, put a message in the info box like "Looking for our current documentation?  Go to https://docs.plone.org".

Thoughts?

P.S.:  I stumbled on the above page just by searching for "glossary":  https://plone.org/@@search?SearchableText=glossary

**Comment by fulv** [comment]
Correction:  I got there by clicking the the [first link](https://plone.org/documentation/glossary) on http://docs.plone.org/4/en/appendices/glossary.html.

**Comment by rioksane** [comment]
I just retracted the page. Its so outdated its not worth fixing.
