### ISSUE TITLE
Rename plone.com on the top toolbar

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#217]
When landing on plone.org you have this black top level navigation that gives you quick access to a few places that one can quickly assume what they are about:

- *this plone thing* organizes a conference/has conferences about it
- *this plone thing* has documentation
- *this plone thing* has some training available
- *this plone thing* has some forums to discuss
- *this plone thing* has some jobs listings
- *this plone thing* has a plone.com ????

Would it make sense to rename it to *showcase/overview/...* or some other buzzword of the day? plone.com does not convey any other meaning comparing to all the other links on that navigation.

**Comment by tkimnguyen** [comment]
Yes, you're absolutely right... I wanted to ensure Plone.com was listed AT ALL on our various properties, and at the time the most appropriate description of what it provides did not come to mind. "Showcase/overview" is indeed the right concept.

**Comment by tkimnguyen** [comment]
When I look at Plone.com I think we are trying to answer the question, "Why Plone?".

**Comment by tkimnguyen** [comment]
..as well as "What is Plone?". I think someone recently mentioned that we do not have a high level sentence or two anywhere on either Plone.com or Plone.org about what Plone is (well, in fact, we have the tag lines). "What can you do with Plone?"...

**Comment by tkimnguyen** [comment]
"About Plone"?

**Comment by gforcada** [comment]
plone.com is gone
