### ISSUE TITLE
LDAP integration (deprecated?)

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#22]
We need to connect the new site with the central Plone LDAP to start make real user tests against the site. Talk with Steve M as the resident LDAP guru.

**Comment by jensens** [comment]
I can offer to use ``pas.plugins.ldap`` and pimp it's the performance branch while doing so. It's already fast with lots of users when accessing single users or groups, except for member listings.

**Comment by sneridagh** [comment]
Paul and me thought about not use LDAP for the new plone.org. Just to simplify things. We have to finish validating this.

**Comment by sneridagh** [comment]
and decided to go to GitHub auth. Working on it right now!
