### ISSUE TITLE
Dead link on Addons page

### ISSUE THREAD

**Issue by sgrepos** [plone/ploneorg.core#220]
On https://plone.org/download/add-ons, the following section has a dead link:

> Learn
> - [how to install add-ons in your site](http://training.plone.org/5/add-ons.html)

The correct URL "how to install add-ons in your site" should point to is https://training.plone.org/5/mastering_plone/add-ons.html

**Comment by tkimnguyen** [comment]
Thanks again @sgrepos! This is fixed.
