### ISSUE TITLE
Minor navigation design issue on Plone.org Community page

### ISSUE THREAD

**Issue by sgrepos** [plone/ploneorg.core#223]
When you're on the [Plone Foundation](https://plone.org/foundation) page, the Plone Foundation button on the navigation is like this:
<img width="398" alt="nav-foundation" src="https://cloud.githubusercontent.com/assets/26908305/25235629/bb580a7a-25b3-11e7-81a3-fa08e2bba506.png">

But on the [Community](https://plone.org/community) page it's like this:
<img width="376" alt="community" src="https://cloud.githubusercontent.com/assets/26908305/25235763/2246caaa-25b4-11e7-8e04-731e50bc9da9.png">

The current HTML on the Community page is showing up as:
`<li id="portaltab-community">`

The "selected active" class should be in the HTML to fix this:
`<li id="portaltab-community" class="selected active">`

cc @tkimnguyen

**Comment by tkimnguyen** [comment]
thx @sgrepos

**Comment by sgrepos** [comment]
No problem, glad to help @tkimnguyen! :)

**Comment by rioksane** [comment]
This seems to be fixed, I'll close the issue. 
![Screenshot 2021-03-21 at 16 15 29](https://user-images.githubusercontent.com/5127672/111908148-c9ad3f80-8a60-11eb-89fe-f479ce623891.png)
