### ISSUE TITLE
Broken link to Archetypes Developer Manual

### ISSUE THREAD

**Issue by tobiasherp** [plone/ploneorg.core#224]
On https://docs.plone.org/4/en/develop/plone/searching_and_indexing/indexing.html#creating-a-metadata-column, there is a link to https://plone.org/documentation/manual/developer-manual/archetypes which doesn't work. Please update the link or migrate the contents. Thank you!

**Comment by jensens** [comment]
may you please report this at https://github.com/plone/documentation/issues

**Comment by tobiasherp** [comment]
Done, thank you.
