### ISSUE TITLE
when making a new Plone release, check correct folder ordering

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#227]
https://plone.org/download/releases uses physical ordering. A visitor reported the releases were out of order https://community.plone.org/t/plone-releases-order-on-website/4109 

We could add a collection to sort by modification date, but then we would be mixing 4.x and 5.x releases. To solve that we could have two collections (in the past we could have used sub collections) and use Display View All Content but then would have to hide stuff. Messy. Suggestions? 

cc @esteele @polyester @loechel

**Comment by tkimnguyen** [comment]
![plone org releases](https://cloud.githubusercontent.com/assets/815418/25536123/29e1944c-2bff-11e7-9658-df77a7f9f10b.png)

**Comment by rioksane** [comment]
The manual ordering seems to be working fine and all releases are in order. I'll close this one.
