### ISSUE TITLE
link to help plone foundation invalid on new installation home page

### ISSUE THREAD

**Issue by laurent4net** [plone/ploneorg.core#229]
New install, 1st page (home) last link on page. Link to help Plone foundation is broken. (https://plone.org/foundation/foundation-donations)

**Comment by laurent4net** [comment]
Possibly correct links should be:
https://plone.org/community/sign-me-up
or
https://plone.org/sponsors

**Comment by rioksane** [comment]
I think the link https://plone.org/foundation/foundation-donations now redirects to https://plone.org/foundation/donors and it looks ok: it has the list of donors and a clear link to Become a Sponsor. So I'll close this issue for now.

**Comment by fulv** [comment]
Oh, boy, the lists on https://plone.org/foundation/donors need a lot of
love.
-- 
Fulvio
