### ISSUE TITLE
two country vocabularies?

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#24]
@sneridagh I see that there are two vocabularies for getting countries from pycountry, is there any need for it?

https://github.com/plone/ploneorg.core/blob/master/ploneorg/core/vocabularies.py
https://github.com/plone/ploneorg.core/blob/master/ploneorg/core/content/foundationmember.py#L16

**Comment by sneridagh** [comment]
@gforcada Not at all, let's unify them.

**Comment by gforcada** [comment]
Done :)
