### ISSUE TITLE
Insufficient Privileges when adding an event

### ISSUE THREAD

**Issue by thet** [plone/ploneorg.core#243]
As user ``thet`` I want to add an event but have insufficient privileges to do so.

https://plone.org/events/community/++add++Event

/cc @tkimnguyen et al, plz help

**Comment by tkimnguyen** [comment]
I fixed it TTW by adding the permissions "CMFEditions: Access previous versions" and "CMFEditions: Save new version" to "Contributor" role at http://localhost:8081/ploneorg/manage_access

**Comment by tkimnguyen** [comment]
I'll close this, but if someone has time and interest in fixing it in code please reopen :)

**Comment by tkimnguyen** [comment]
maybe https://github.com/plone/ploneorg.core/blob/master/ploneorg/core/profiles/default/rolemap.xml
