### ISSUE TITLE
Dead link on "Extend Plone's Power with Add-Ons" page

### ISSUE THREAD

**Issue by sgrepos** [plone/ploneorg.core#244]
On https://plone.org/download/add-ons, the following section has a dead link:

> Learn
> - [how to install add-ons in your site](https://training.plone.org/5/mastering_plone/add-ons.html), and

The updated link to the page it's supposed to point to is at https://training.plone.org/5/mastering-plone/add-ons.html

Seems that page is cursed haha, I remember opening this issue before and @tkimnguyen fixing it 😂

**Comment by tkimnguyen** [comment]
thanks @sgrepos – fixed now!
