### ISSUE TITLE
Broken links on Plone Event and Sprint Sponsorship Page

### ISSUE THREAD

**Issue by sgrepos** [plone/ploneorg.core#245]
- [x] Second bullet under the Types of Events sub-heading, with the "teams" link is broken. It should be updated to https://plone.org/community.

- [x] Under the "Reporting Back" sub-heading, the link to https://plone.org/foundation/event-sponsorship/plone-event-report-form is broken.

**Comment by tkimnguyen** [comment]
Thanks @sgrepos - I've recreated https://plone.org/foundation/event-sponsorship/plone-event-report-form based on what is on the old.Plone.org site

**Comment by tkimnguyen** [comment]
@sgrepos and I've fixed the broken teams link - thank you!
