### ISSUE TITLE
Content Type Link did not work on plone.org

### ISSUE THREAD

**Issue by loechel** [plone/ploneorg.core#250]
If you have a Linkt content type object, the view page did not directly forward you to the link target, but just show the link, even if you are not logged in.

**Comment by tkimnguyen** [comment]
ok, Links on plone.org work correctly now... it really was just that I had to enable immediate redirection for Links in the Content Types control panel (that simple, duh).

the discussion that brought it up: https://community.plone.org/t/plone-4-3-and-automatic-csrf-protection/7290/20
