### ISSUE TITLE
News and Events

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/ploneorg.core#26]

**Comment by gforcada** [comment]
Is there any specific coding needed here? Migration of old content? A new content type? Just adapting the default ones is enough? Templates should be created?

**Comment by 3dogMcNeill** [comment]
To put the newsletter on the current plone.org, I copy it in plaintext and paste it into Plone, then reformat headings, paragraph spaces, and urls. It doesn't take terribly long, but if a couple of steps could be eliminated, or if we could automagically make it appear in the new plone.org, that would be great. https://apidocs.mailchimp.com/

**Comment by 3dogMcNeill** [comment]
Off the top of my head, I don't see a need to alter the news or event content types.

**Comment by fulv** [comment]
Going forward, do we want to have just a link to the mailchimp page of the newsletter, or a copy of the whole text?

**Comment by 3dogMcNeill** [comment]
that's a good question. Having it on the site helps with SEO, but
ultimately detracts from subscribers. I think I should confer with some
people about this and more thought into the strategic direction for the
newsletter.



Christina

**Comment by 3dogMcNeill** [comment]
add pics to events; stick with plone.app.contenttypes
