### ISSUE TITLE
Long titles or descriptions throw off the tiled design

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#260]
for example https://plone.org/support, https://plone.org/security

**Comment by rioksane** [comment]
Improved titles on those sections to be shorter. 

I think fixing this can wait for a bigger overhaul in theming.

**Comment by rioksane** [comment]
I think it looks pretty good in various screen sizes. Closing this issue for now.  
![Screenshot 2021-03-21 at 17 05 18](https://user-images.githubusercontent.com/5127672/111909915-d5e8cb00-8a67-11eb-86fd-13aa80ba94a7.png)
