### ISSUE TITLE
Top level folders that get the tiled design should have fewer tiles (9 max?)

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#261]

**Comment by rioksane** [comment]
I think this could be fixed just by editing content so that the amount was limited to 9. Oh well https://plone.org/community has many more, but if we moved Teams under one folder, it would fix this problem

**Comment by rioksane** [comment]
Closing this issue. Its ok that community has more tiles. On the others, we can edit the content.

**Comment by skleinfeldt** [comment]
@rioksane Shouldn't we leave this open to remind us to edit the content? That's what this ticket is about I think.

- [x] Community - reorganized and we are OK with more than 9
- [x] Foundation (Someone should make sure this info is still correct and the tiles are in the right order)
- [x] Support (Local User Groups probably outdated)
- [x] Chat (it is under support and also a More menu item - consolidate?)
- [x] Providers (on More menu but currently empty, not a good look)
- [x] Related Websites (reconsider link to plone.com, Planet Plone [although it is currently working])
- [x] Security (reconsider link to plone.com and whether the tile order makes sense, visit all links and update as appropriate [Security Team membership isn't up to date])
- [x] Sponsorship (still a WIP or done? Consider moving About Sponsorship info to the top?)

I'm going to reopen but feel free to open another ticket with this if you think that would be better.

**Comment by rioksane** [comment]
- Support: I hid local user groups from the support page as outdated
- Foundation: order is correct, every public tile (10) seems to be valid. 
- Chat hidden under more-menu
- providers points to https://plone.org/providers and is not empty and is up to date
- related websites has now 8 links in order. Hid planet plone. Renamed a couple of links for better order. 
- security has 9 tiles in order so it looks good
- sponsorship - Can't see a related issue here, this not being a tiled page https://plone.org/sponsors
@skleinfeldt I will close this issue now, I think I got everything from the checklist

**Comment by skleinfeldt** [comment]
Hooray @rioksane !
