### ISSUE TITLE
News item listing shouldn't bother to use images unless they are better curated

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#262]
(same aspect ratio/size, made with p.a.imagecropping)

**Comment by rioksane** [comment]
We did improve this later in 2020, at least in instructions. 4:3 aspect ratio https://plone.org/news/plone-org-style-guide

Latest 2020 news items look ok in the list. 

However, it would be better if the images were resized by the site style.

**Comment by rioksane** [comment]
Sally fixed the latest news item images. 
Norbert is working on adding p.a.imagecropping to plonbe.org, which probably fixes the issue once and for all.
Marketing team is well aware of image ratio issue and will monitor news items. 

I will close this for now.
