### ISSUE TITLE
https://plone.org/community  needs love 

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#268]
1. Header says it's about the teams but it's actually a mix of stuff - should get a reorg to be more logical and tiles fit on one page
2. GSoC is a tile here and also a "More" menu item - should be one or the other (and GSoDocs should mimic)
3. Sign me up for the newsletter is sadly irrelevant now
4. Paragon is no longer and should be removed
5. Plone.com should be removed?
6. Is PloneEDU still a thing? broken link to form at the bottom of https://plone.org/community/edu/stories

**Comment by rioksane** [comment]
1.  I reorganized content in alphabetical order. Think its better now. 
2.  I think it's not that bad that GSOC is here too. Its just a link here and in the more -menu, they go to the same place
3. Newsletter link comes through the theme somehow :/
4. paragon seems to be removed
5. plone.com is another discussion, but will be removed. 
6. PloneEDU is now hidden.

**Comment by rioksane** [comment]
I excluded gsoc from the list for 2021. Lets put it back if it continues.

**Comment by rioksane** [comment]
Community page has seen some love. Will close the issue now
