### ISSUE TITLE
plone.org/foundation issues

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#269]
1. Foundation News is ancient
2. Why are Logo and Foundation Sponsors link objects here in the same folder as the things they point to? (Both link and linked object show redundantly on page)

**Comment by rioksane** [comment]
1. I couldn't find foundation news anymore. Maybe it's already removed. 
2. I made the redundant links private. They were linked to old meeting minutes from 2008. So I didn't dare to remove. 

3. Archives should be hidden https://plone.org/foundation/copyright-licensing-logo/archives/

**Comment by rioksane** [comment]
I set logo archives as private. Will close this issue now.
