### ISSUE TITLE
Chat on the "More" nav

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#271]
Chat on the "More" nav goes to plone.org/support/chat so is already accessible from Support. But maybe we want to highlight Chat on the nav, in which case the page should get a rewrite to be clearer and put the most important stuff at the top.

**Comment by rioksane** [comment]
I think now that Chat could be hidden from More-menu: 
- It's already accessible through the Support page and more importantly
- Chat page doesn't seem to be sho welcoming now..? The sentence "Please do not use chat to ask for support" is repeated many times and the first title is "GSoC students: do not use chat."

**Comment by rioksane** [comment]
I changed the order of subtitles on the chat page. Hope its better.

**Comment by skleinfeldt** [comment]
I agree that Chat should be hidden from More menu, and that the page needs some attention. For example at this point lots of people are using Slack but that is not mentioned...

**Comment by rioksane** [comment]
OK, chat is hidden from the More-menu, but still accessible from https://plone.org/support/ and also the page https://plone.org/support/chat has been slightly improved. I'll close this issue.
