### ISSUE TITLE
Info-banner for outdated content

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#279]
We need a way to insert a banner on top of outdated pages to inform visitors that this content is here for historical purposes only, and no longer active.

e.g. https://plone.org/community/communications-and-marketing/marketing-committee/kudobountyprogram

**Comment by rioksane** [comment]
I would just state that fact in a description field or in the title. Which I did. 

Although, I would vote for hiding the whole section https://plone.org/community/communications-and-marketing/marketing-committee (its titled OLD) and contains stuff from 2009 or so. Hardly relevant to keep public?

**Comment by rioksane** [comment]
I changed that folder and its contents private. 

I'll close this issue: outdated content should be hidden OR we can just state that its outdated in the title or description.
