### ISSUE TITLE
Where is the current 5.2.3 ?

### ISSUE THREAD

**Issue by robertherzog** [plone/ploneorg.core#288]
I am really surprised that, for several months now, the latest "release 5.2.3" is unavailable on the main Plone website, even if it mentions on a bright red background "Get Plone 5.2 (stable)", which links to 5.2.3 on Github. I know it is possible to find 5.2.2 but giving a link to an unexisting package is not very stimulating to get using Plone. 
I have been using Plone over the most of last decade, I run several sites on 5.1. I witnessed that the support has been steadingly vanishing.
This is sad.
Greetings from sunny, but icecold Belgium
Robert

**Comment by fulv** [comment]
Thanks for your report, but this is the wrong repo for this issue.  
If you want to file your report as a github issue, the proper repo would be https://github.com/plone/Products.CMFPlone/issues.

But you will probably get more attention by posting to community.plone.org.
