### ISSUE TITLE
Move all sponsors from /sponsors/sponsor-database to /sponsors.

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#289]
The plan is to move all providers and sponsors form plone.com to plone.org.  I have already manually updated all the content items in plone.org/sponsors/sponsor-database, and the [foundationsponsor.pt](https://github.com/plone/ploneorg.core/commit/7ede5e5150e0fbed4370693e7ab8e36aac8dc06e) template.  The other piece is to install nginx redirects on plone.com, such as:

```
  rewrite ^/providers/premium/soliton-consulting.html https://plone.org/sponsors/sponsor-database/soliton permanent;
```

However, you can see the problem in the above redirect: it would be irritating to see that `/sponsor-database/` in a sponsor URL. 

Thus, I propose the following:

Move all sponsor items and collections from `/sponsors/sponsor-database` to `/sponsors`, since `sponsor-database` is nothing but a regular folder.  Currently, there are only five other items, in addition to the database, in `/sponsors` (two of which can be deleted soon), so we won't be mixing things too badly:

![Screenshot 2021-02-10 at 17 26 36](https://user-images.githubusercontent.com/460742/107580936-3a348700-6bac-11eb-981c-6c3a4b2c10ed.png)

Then we can use the redirects from https://github.com/plone/aiteam/commit/6297d3c48d774267ad9f98544ed9748855931384.

Objections?

@tkimnguyen @ericof

**Comment by ericof** [comment]
@fulv Perfect, go for it

**Comment by fulv** [comment]
I have double-checked that the /sponsors/sponsor-database path is not hard-coded or configured in any of the following:

- [ ] collections
- [ ] browser views (catalog queries)
- [ ] content rules
- [ ] templates

**Comment by fulv** [comment]
Reminder to:

- [ ] replace `sponsor/provider_listing_url` with `sponsor/absolute_url` in all the sponsors and providers browser view templates

so that we don't send people to the plone.com listings anymore, only to be redirected back to plone.org by nginx.

**Comment by fulv** [comment]
I've decided to leave the collection items in the `/sponsors/sponsor-database` folder and to keep the folder itself, so it can be used with its collection portlets.

**Comment by fulv** [comment]
This is done.
