### ISSUE TITLE
Carousel too wide on mobile

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#36]
I looked at new.plone.org on my phone and everything is nice and responsive, except for the carousel.  It seems to keep its full width, so the page has some horizontal scrolling, which is not good.

**Comment by lhuiskes** [comment]
I created this standalone responsive carousel which still needs to be implemented, but you can already check it out!
https://gist.github.com/lhuiskes/b55a2e993198c95b9d3f

**Comment by allcaps** [comment]
This landed in master.

@lhuiskes: It's an improvement but still needs some work. 

1) The running paragraph text is distracting. Can we hide and show it on focus? I can imagine that the text width consistent with the slide width can be also an improvement.
2) When changing view port size the re-initialise does not get the right slide width.

**Comment by lhuiskes** [comment]
Fixed the resized bug
