### ISSUE TITLE
Menus on mobile

### ISSUE THREAD

**Issue by fulv** [plone/ploneorg.core#37]
On a small screen, I noticed two issues with the navigation:

1. There are two navigation menus:  one in the top left with the label "Menu" with a dropdown containing plone.org, solutions, documentation and discussion;  and one in the blue banner on the right side, which has a hamburger icon, and contains new to plone, plone cms, add-ons, support, foundation, and log in.  It's a bit confusing to have two menus, so either one needs to be removed, or they should be merged into one.
2. The buttons are too small for mobile.

**Comment by RobZoneNet** [comment]
Working on this now

**Comment by sneridagh** [comment]
Closing this as Coen's prototype will take care of this.
