### ISSUE TITLE
Contributor/community member pages

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#4]
We want to have a rich contributor and community member profile pages, allowing to show the personal stats based on several sources (GitHub, StackOverflow, etc).

~~**UPDATE**: Initial work done with hero image. It is needed some love though.~~

**Comment by sneridagh** [comment]
We decided not to have a hero photo.

**Comment by polyester** [comment]
duplicate of https://github.com/plone/ploneorg.core/issues/21
