### ISSUE TITLE
"New to Plone" section

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#40]
This is the former "Get involved" in current plone.org. It should contain the "Mozilla-like" layout for the section page, and should contain this content:

* Contribute
* Get help
* Community structure
* Affinity groups
* Donate

For the subcontent, please check current plone.org and https://docs.google.com/spreadsheets/d/1bwMCHbWfxVj3-BVyCA4RpMq7ZTfycSaqJ7p1dizn1EU/edit#gid=0

**Comment by 3dogMcNeill** [comment]
refer to issue #18

**Comment by 3dogMcNeill** [comment]
see Issue #40

**Comment by 3dogMcNeill** [comment]
folded into Issues #18 and #42. Closing.
