### ISSUE TITLE
"Support" section

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#42]
Stays the same as the one in plone.org. It is required some review and transfer styles. It should contain:

* Plone Support Center
* Chat Room
* Comercial support
* Training Announcements
* Reporting bugs

More info: https://docs.google.com/spreadsheets/d/1bwMCHbWfxVj3-BVyCA4RpMq7ZTfycSaqJ7p1dizn1EU/edit#gid=0

**Comment by 3dogMcNeill** [comment]
Editing content down to include:
- Plone Docs
- Stackoverflow
- Chat
- Local Users Groups

(Get) "training" will be moved to plone.com; contributing to "training" will become part of Issue#

**Comment by 3dogMcNeill** [comment]
local users group info removed b/c not necessary for site launch. New issue created. See #60.

**Comment by 3dogMcNeill** [comment]
incorporate in Plone 5

**Comment by tkimnguyen** [comment]
Should we incorporate feedback based on @cdw9 's human experiment?

**Comment by 3dogMcNeill** [comment]
Think most of those have been considered but it's always helpful to have a list!
