### ISSUE TITLE
"Join" action missing

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#44]
We need to place a "Join" somewhere. Maybe in "New to Plone" page.

**Comment by 3dogMcNeill** [comment]
related to issue #18

**Comment by sneridagh** [comment]
If we are going to have Github.com authentication in plone.org, then the join should be explained in the login page.

**Comment by sneridagh** [comment]
Find the correct place in the new mockup.

**Comment by allcaps** [comment]
Yes, a simple overlay is likely to be sufficient...
<img width="950" alt="screen shot 2015-11-24 at 00 21 46" src="https://cloud.githubusercontent.com/assets/1969342/11353230/a6b1b5b4-9241-11e5-9cc8-435df61d9067.png">

**Comment by allcaps** [comment]
@sneridagh,

Clicking 'login' in the global nav will be basically trigger the 'sign up' proces. The first time you have to authorise Plone.org on Github. Every other time after that there is an instant login (as long as you are signed in at Github). Or this is at least my understanding. Right?

A profile in plone.org will give you 1) a profile page 2) the ability to submit events. So I suggest that at the pages that have login relevance (profile listing, profile detail, badge listing and add event form) we also add a sign up text. The link should trigger the same modal as login does.

**Comment by allcaps** [comment]
#55 is related.

**Comment by allcaps** [comment]
I added a login modal to the theme. 
https://github.com/plone/ploneorg.theme/commit/f436b36397a859f957057424f4740a358f9d880f

![out](https://cloud.githubusercontent.com/assets/1969342/11410744/2e965b54-93ca-11e5-840a-e2d2f4613118.gif)

**Comment by sneridagh** [comment]
We need to do the proper wording to the modal.

**Comment by sneridagh** [comment]
Ok #55 replaces the remainings of this.
