### ISSUE TITLE
"Events" and "News"

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#45]
The sections need to be curated and the layout decided. Left, right portlet?

**Comment by 3dogMcNeill** [comment]
The news folder has been a mess for a very long time. If nobody minds, I'd like to sort (using Collections probably) old news items by year and have the years listed in a portlet. 

When viewing a Collection in "Summary View," we need to get rid of the "read more" links.

**Comment by 3dogMcNeill** [comment]
Will work on after Issues #46 and #47 resolved

**Comment by 3dogMcNeill** [comment]
imported content does not include publication dates—makes it difficult to create collections and organization decades of news

**Comment by 3dogMcNeill** [comment]
News folder organization is complete.

**Comment by sneridagh** [comment]
@3dogMcNeill this issue could be closed then?

**Comment by 3dogMcNeill** [comment]
yes!
