### ISSUE TITLE
Stats sources retriever

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#5]
We need a kind of engine that retrieves all the needed stats proposed to be in the contributors/community members profile pages. This engin should be the least intrusive possible and is desireable to make the job in a nightly, deferred job.

M.Wilkes already has an initial implementation for retrieving/showing some data from several sources called mr.cabot (https://github.com/collective/mr.cabot).

**UPDATE**: Some initial work it's already done on this. Now two sources are working: GitHub and Stackoverflow. More integrations need to be done, like Gmane, Twitter or the new posts in community.plone.org.

**Comment by 3dogMcNeill** [comment]
Can this issue be split into Homepage Stats and Contributor Stats?

**Comment by tkimnguyen** [comment]
Would be lovely to have contributions captured from non-code sources, e.g. community involvement... (but how?)

**Comment by aclark4life** [comment]
@tkimnguyen Depends on what kind of community involvement. Maybe you could get some data from community.plone.org CC: @martior

**Comment by tkimnguyen** [comment]
IRC, emails to lists not moving to the forum, general sh*t disturbing (speaking about myself) is hard to quantify, etc.

**Comment by sneridagh** [comment]
Attendance to sprints (with the new CT), Plone Confs, Tune-ups, etc.

**Comment by polyester** [comment]
I'll take a look at integrating https://community.plone.org posting stats

**Comment by 3dogMcNeill** [comment]
Need to define what stats to show on the homepage

**Comment by polyester** [comment]
I'll also ask Sven, he's been working on statistics for the documentation.

**Comment by sneridagh** [comment]
Should we separate the issues regarding the sources we are already working on (Github, StackOverflow, community.plone.org)? It seems they will have its own life cycle.

**Comment by gforcada** [comment]
:+1: at @sneridagh proposal, let's keep it simple

**Comment by gforcada** [comment]
Closing, open specific issues for each stat that is missing
