### ISSUE TITLE
Dealing with spammers on plone.org

### ISSUE THREAD

**Issue by jean** [plone/ploneorg.core#51]
It doesn't happen a lot, but every now and then an idiot registers at plone.org and starts submitting spam sites. 

Quick action: as content reviewer, I don't have rights to deactivate/delete users. Could we make it easier for content reviewers to block/flag bad users?

Regarding mechanism, is there anything existing for Plone for restricting deleted spammers from signing up again? E.g. blacklist email addresses, or quarantine new users (first time content submission triggers membership review).

@tkimnguyen yo :-)

**Comment by tkimnguyen** [comment]
@3dogMcNeill is this issue being tracked elsewhere? It may be something we want to have in the new Plone.org

**Comment by 3dogMcNeill** [comment]
It was decided as a non issue with Plone 5 so I closed it.

On Friday, October 30, 2015, T. Kim Nguyen <notifications@github.com> wrote:

> @3dogMcNeill <https://github.com/3dogMcNeill> is this issue being tracked
> elsewhere? It may be something we want to have in the new Plone.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/ploneorg.core/issues/51#issuecomment-152647070>.
>


-- 
Sent from my iPad
