### ISSUE TITLE
ploneorg.admin: issue tracker?

### ISSUE THREAD

**Issue by jean** [plone/ploneorg.core#52]
The https://github.com/plone/ploneorg.admin repo doesn't have issues activated, and as description only has a link to http://developer.plone.org/reference_manuals/external/ploneorg.admin/index.html which is a 404. 

Clarify on the repo what tracker to use, and update the link to current docs.

**Comment by jean** [comment]
Created https://github.com/plone/ploneorg.admin/pull/1 to point out `ploneorg.core`

**Comment by gforcada** [comment]
Merged by @svx
