### ISSUE TITLE
Login: Make popup and add description

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/ploneorg.core#55]
1. Content:
login will require github account so users will need to have a github account or go to github and sign up for one before they can login to plone.org. This needs to be explained on the same page or pop up as the login credentials 

2. Make this a pop-up instead of a page

**Comment by polyester** [comment]
text added in https://github.com/plone/ploneorg.theme/commit/2a71e1818cdcc8f9c7c7473c7413e8e467e192dc
