### ISSUE TITLE
Remove H1 format from TinyMCE

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/ploneorg.core#58]
both have the same visual styling

**Comment by 3dogMcNeill** [comment]
h1 is not defined in TinyMCE formats in site setup but is visible in both "format" buttons (see images below) 
<img width="658" alt="screen shot 2015-10-17 at 3 46 15 pm" src="https://cloud.githubusercontent.com/assets/7101218/10558803/5ae16904-74e6-11e5-8c09-dd9831c38e8f.png">
<img width="495" alt="screen shot 2015-10-17 at 3 46 28 pm" src="https://cloud.githubusercontent.com/assets/7101218/10558804/5ae27ef2-74e6-11e5-80d8-947a8fb4980b.png">

**Comment by sneridagh** [comment]
Take a look in Plone 5 if this is still required/happening.

**Comment by 3dogMcNeill** [comment]
still there

**Comment by gforcada** [comment]
Fixed! I just removed a line on http://new.plone.org/@@tinymce-controlpanel in header styles
