### ISSUE TITLE
Stats boxes do not have the same size

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#64]
See screenshot:

![ploneorg](https://cloud.githubusercontent.com/assets/1155680/10558530/dacae0c0-74da-11e5-8742-561a8c51d7ee.png)

If the stat number is less than 10 the icon is next to it, as soon as it gets above 10 the icon is moved below. As it will be a ever changing number it can happen that there are small numbers, so making all boxes look the same no matter how big or small is the number would be better, right?

**Comment by sneridagh** [comment]
Yes, we should look into this. Once the actual content is in place, we can opt for the best solution, probably make the icon drop always at the bottom in its own line.

**Comment by 3dogMcNeill** [comment]
should be resolved with new theme. closing.
