### ISSUE TITLE
Alert shows up twice in control panel

### ISSUE THREAD

**Issue by jean** [plone/ploneorg.core#65]
The `alert` div shows up once as a child of `#globalstatusmessages` and again just after `#documentDescription`.

This is the div I mean:
```
  <div class="alert alert-dismissable alert-info"><button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>...</div>```

**Comment by sneridagh** [comment]
This should be fixed in Plone 5 version.

**Comment by sneridagh** [comment]
Confirmed it's solved.
