### ISSUE TITLE
Remove bullets from folder_summary_view

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/ploneorg.core#66]

**Comment by 3dogMcNeill** [comment]
<img width="682" alt="screen shot 2015-10-17 at 2 28 03 pm" src="https://cloud.githubusercontent.com/assets/7101218/10558540/67214136-74db-11e5-86aa-d45036c8fd8b.png">

**Comment by RobZoneNet** [comment]
This seems to be fixed in the current iteration
