### ISSUE TITLE
Import Foundation Members

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/ploneorg.core#68]
names of members were imported but none of their information was imported

**Comment by tkimnguyen** [comment]
...and it seemed that members in Draft or Rejected state had "[...]" as the title instead of the person's name, as was the case with other imported members

**Comment by sneridagh** [comment]
I think I've already fixed this in Plone 5 version. However, there still some improvements to be made on the main views.

**Comment by tkimnguyen** [comment]
Looking at (say) http://new.plone.org/foundation/members/limi and https://plone.org/foundation/members/limi/ was it intentional to import just name, company, city, and country? (if you're logged in the limi object on current plone.org has a lot more detail).

**Comment by sneridagh** [comment]
The information is migrated (which is the most important point), although the main view need some more love :P

**Comment by 3dogMcNeill** [comment]
log new issues for theming needs.

**Comment by tkimnguyen** [comment]
Should I be checking at (say) http://new.plone.org/foundation/members/limi ? Getting "This page does not seem to exist…"
