### ISSUE TITLE
The toolbar does not show on tablets and phone sizes

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#7]

**Comment by RobZoneNet** [comment]
The searchbox and "sites-select" are currently hidden but the other part of the toolbar is put in a "Menu" pull down.  I think we should always show the searchbox and probably sites-select(within the Menu button).

**Comment by sneridagh** [comment]
Actually I can't remember why it's hidden, maybe because of responsiveness issues.

**Comment by sneridagh** [comment]
I'm closing this, as Coen's prototype will take care of it.
