### ISSUE TITLE
Reimplement the toolbar for not to use the JS async loading

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#70]
If you put TinyMCE in full screen view, the menu gets hidden by a black bar from the theme (I think).
![screen shot 2015-10-17 at 3 29 03 pm](https://cloud.githubusercontent.com/assets/815418/10558735/e9fee6a0-74e3-11e5-9f6f-3aa2df857c1c.jpg)

**Comment by sneridagh** [comment]
Check if this is happening in Plone 5 as well.

**Comment by 3dogMcNeill** [comment]
still happening in Plone 5

**Comment by sneridagh** [comment]
Full screen tinymce view menu is hidden by the black toolbar. This is originally thought as a shared component loaded via a JS async script for its use in the diferent local (plone.cat, plone.de, etc) sites.

We finally decided to ditch it and use a pure theme component.

We should take care that it does not happens in the new prototype.

**Comment by sneridagh** [comment]
It got revamped in the new theme. Closing it.
