### ISSUE TITLE
catalog search to create internal link not responsive

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#73]
Trying to edit this static text portlet to set the internal link to the "become a sponsor" page in the /sponsors folder... clicking in the search widget causes the spinner to spin but it never comes back. May be a temporary glitch?

http://new.plone.org/sponsors/sponsors/++contextportlets++plone.rightcolumn/become-a-sponsor/edit?referer=http%3A//new.plone.org/sponsors/sponsors/%40%40manage-portlets

**Comment by sneridagh** [comment]
Hope to be fixed in Plone 5.

**Comment by 3dogMcNeill** [comment]
seems resolved in Plone 5.
