### ISSUE TITLE
We need stats from plone.com

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#75]
@3dogMcNeill we need some basic data for the front page:
- number of solution providers
- number of countries

**Comment by 3dogMcNeill** [comment]
the solution providers is updating rather regularly—is there an automated way to get the count or are you ok with a static count?

**Comment by polyester** [comment]
I'd actually prefer a static count at this moment in time.

**Comment by 3dogMcNeill** [comment]
rest of stats for homepage are related to #34
