### ISSUE TITLE
Migration of data from old website

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#76]
The migration needs to be done once again and checked that everything still works.

Ask @sneridagh on how to get the data from the previous website if you are interested in this issue.

@sneridagh a guide on what has to be done to do a migration and what to check to verify that the migration was successful would be a great help.

**Comment by sneridagh** [comment]
A fresh (and hopefully the last one to be made) is on new.plone.org :) I think everything is in place. The migration guide was on the README of the ploneorg.core if anyone wants to check it out.
