### ISSUE TITLE
PAS plugin to user github login

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#77]
To not have to, yet again, remember another user and password (and as an extra benefit not having to rely on Plone's LDAP) a PAS plugin that interacts with GitHub will be used as a replacement.

@jensens is working on it, get in touch with him if you are interested in this issue.

**Comment by jensens** [comment]
wip here https://github.com/collective/pas.plugins.authomatic

**Comment by gforcada** [comment]
Cool!

**Comment by sneridagh** [comment]
I've already put and configured it in new.plone.org. We need an account (Plone community bound) of Github for the tokens.

**Comment by jensens** [comment]
Login works, missing parts are documented at
https://github.com/collective/pas.plugins.authomatic/issues

**Comment by jensens** [comment]
@sneridagh i sent you the github token for plone by mail.

**Comment by 3dogMcNeill** [comment]
just tried to login with github: got message about untrusted certificate, after clicking to accept the risk, got (only) this message in my browser window, "The redirect_uri MUST match the registered callback URL for this application."

**Comment by sneridagh** [comment]
Yeah, you should access first to the full URL with https:
https://new.plone.org/login

Then follow the same steps you did before but starting with https.
V.

**Comment by 3dogMcNeill** [comment]
ok, that worked, thanks!

**Comment by gforcada** [comment]
An nginx/apache redirect to SSL on /login form probably would help here as well :)

**Comment by sneridagh** [comment]
It seems someone took care of it as it's already in place! Thanks!

**Comment by 3dogMcNeill** [comment]
I don't know if this is related or a new issue—since Github login, after I navigate away from the you're-logged-in page, the toolbar disappears. It does not reappear on any page in the site.

**Comment by sneridagh** [comment]
It's very strange! You and me have the same roles (Manager) and the toolbar
behavior is the one expected. :(

**Comment by jensens** [comment]
Looks like the auth-tkt cookie was not set correctly.
May you check in the developer toolbar if the ``_ac`` cookie is present?

**Comment by 3dogMcNeill** [comment]
I'll check that. I do have custom cookie settings so that may it.

On Saturday, November 7, 2015, Jens W. Klein <notifications@github.com>
wrote:

> Looks like the auth-tkt cookie was not set correctly.
> May you check in the developer toolbar if the _ac cookie is present?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/ploneorg.core/issues/77#issuecomment-154666555>.
>


-- 
*Christina McNeill*
IRC: cmcneill

**Comment by jensens** [comment]
If you want github users having global role ``Member``:

- in ZMI go to Plones ``acl_users`` -> ``portal_role_manager`` 
- click on ``Member``
- click on ``Assign``
- search for principal id ``Auth``
- select and move ``Authenticated Users (Virtual Group)`` from left to right.
- done

**Comment by jensens** [comment]
I changed some fundamentals of the plugin such as the way the users are stored in order to enable multiple external identities per user. Since this is all alpha I did not provide a upgrade step.

If youre running on ``master`` In existing instances 
- save the json configuration to a local file
- uninstall the plugin, check if ``authomatic`` in ``acl_users`` is gone (if not delete it) 
- install the plugin
- restore configuration
- go to configuration, check it, choose o way iserid are generated.

Sorry for any inconvinience.

**Comment by sneridagh** [comment]
@jensens is this procedure already applied on the staging server?

**Comment by jensens** [comment]
@sneridagh no

**Comment by sneridagh** [comment]
@jensens What is the difference between the three options? Which is the one that was default in the previous version? Thanks!

**Comment by jensens** [comment]
I guess you mean the option how the userid is created?
In the previous version it took the userid form github (or any connected service).
If we're sticking to github only (also future wise) using the userid is fine.
If we're planning to use an additional provider in future the UUID option is the better choice.

**Comment by sneridagh** [comment]
The plugin is now stable and working, so closing this now.
