### ISSUE TITLE
Add plone.app.vulnerabilities to new plone.org

### ISSUE THREAD

**Issue by loechel** [plone/ploneorg.core#81]
plone.app.vulnerabilities add several views and Informations to plone.org like https://plone.org/security/hotfixes, https://plone.org/security/hotfix_feed and https://plone.org/security/hotfix_json last view is implemented but not active on on the current setup.

This gives the Plone Security team the possibility to show the Plone versions that are under active security support, under active maintenance and which Hotfix have to be applied to a specific version to be at current security level. The JSON API gives possibility to implement a active check in a plone instance, as done with plone.vulnerabilitychecks.*  

It also has a hook to send mails to Plone Announcement List if a new Plone Hotfix will be announced.

**Comment by sneridagh** [comment]
The product is in place and the existing content is migrated into new.plone.org (now based on Plone 5!)

**Comment by loechel** [comment]
Thank you,
Content was migrated, but not the metadata from Plone Registry. Now, copied into new.plone.org and migrated content adjusted.

**Comment by sneridagh** [comment]
Oh I wasn't aware of that! So you've already did it? Thanks! Please tell me if there's something else to be done!

**Comment by loechel** [comment]
Yes I already updated new.plone.org. I hope you don't mind.

**Comment by sneridagh** [comment]
Of course not!! Thanks!
V.
