### ISSUE TITLE
How do we map old ownership/local-roles/... to new github account?

### ISSUE THREAD

**Issue by jensens** [plone/ploneorg.core#85]
We need some way to map old userids to the new github based ones. 
We could just transfer the ownership. But we need some mapping/script/.... to do so.

**Comment by sneridagh** [comment]
We already decided not to transfer any user from the original site. I think we could live with the new numeric GitHub ID, however, we should hide it from everywhere and make all the user searches "displayName" aware.

Transfer the current GitHub avatar will be also nice.

**Comment by jensens** [comment]
Just be aware that old owner ids are present in the new system on the content unless you replace them on import.
