### ISSUE TITLE
Slider content

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/ploneorg.core#87]
1. repurpose some of the Plone 5 posters to fill some of the sliders
2. See if group conference photo will fit/look nice
3. Create an advertisement for plone.com

**Comment by tkimnguyen** [comment]
Will we have an equivalent to the premium sponsorship carousel & banners on the current plone.org front page?

**Comment by 3dogMcNeill** [comment]
TBD, I think. Specific issue is #90

**Comment by sneridagh** [comment]
We finally ditched the slider on the new mockup, so I'm closing this.
