### ISSUE TITLE
Home page - General

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#9]
UPDATE (23/11):
What is left:
- [ ] Boxed content, decide the content
- [ ] Put in place the dynamic stats retrievals nightly executed
- [ ] Check all the links
- ~~Accordion powered content with photos and descriptions~~
- ~~Toolbar, the search pane got a bit messed up. Fix it.~~

**Comment by gforcada** [comment]
Could someone (@sneridagh) update this issue to match the actual things missing? :)

**Comment by sneridagh** [comment]
Ok, I'll take a look at it tonight.

**Comment by RobZoneNet** [comment]
I think we need to use this version of zAccordion for its responsiveness http://www.armagost.com/zaccordion/a-responsive-example-using-media-queries/   or not show it at all for the mobile sizes.  What do you all think?

**Comment by jensens** [comment]
``Build the dynamic (stats) part of the page`` is adressed by #31

**Comment by jensens** [comment]
``Build the dynamic (stats) part of the page`` is ready for merge in by #31

The numbers of providers, countries and languages is just content for now. If there is a place to fetch from this can be added later.

**Comment by sneridagh** [comment]
@robzonenet I think it will be strange if the overall site is responsive and this element don't. Indeed, I think that we should use the responsive version of the plugin.

**Comment by sneridagh** [comment]
Anniversary sprint update:
* Now the homepage is linked to the retrieved stats
* The events and news portlets are working too
* Solved some CSS issues and prettify some other parts and responsiveness, specially the personaltools
* Backported the defaultUser.png from Plone 5

**Comment by sneridagh** [comment]
Last touches to the homepage are in place. There is need of think about the content we should put on the grey and blue boxes. There still needed the items in the description.

**Comment by sneridagh** [comment]
Updated! (See main description for the things left)

**Comment by 3dogMcNeill** [comment]
creating a new issue for slider content

**Comment by 3dogMcNeill** [comment]
what's left is in new theme and slider has been abandoned. closing.
