### ISSUE TITLE
New i18n team page

### ISSUE THREAD

**Issue by vincentfretin** [plone/ploneorg.core#94]
The current https://plone.org/community/teams/i18nTeam page is very old.
The most up to date i18n team is in this file:
https://github.com/collective/plone.app.locales/blob/master/docs/TRANSLATORS.html
Not very readable isn't it. (click on Raw, save it and reopen it with your browser)
How the new plone.org handle the different teams?

**Comment by sneridagh** [comment]
Each team will have its own dedicated page. The final implementation is not in place because it will rely on collective.workspaces which it's not in place yet. When we populate them, we will contact with all the team leaders.

**Comment by vincentfretin** [comment]
ok
