### ISSUE TITLE
Merge donate and donate/donate

### ISSUE THREAD

**Issue by allcaps** [plone/ploneorg.core#96]
These pages have duplicate content.
https://plone.org/donate/
https://plone.org/donate/donate

Maybe rename the page id as well to `sponsors`?

**Comment by tkimnguyen** [comment]
I think /sponsors has a different meaning (to show sponsors), whereas /donate is a call to action that I have been sending to people who are thinking of donating.

**Comment by polyester** [comment]
they are combined now, what is needed is a rewrite from /donate to /sponsors
