### ISSUE TITLE
CT Homepage

### ISSUE THREAD

**Issue by allcaps** [plone/ploneorg.core#97]
I'll add a custom content type homepage. To make the various text areas editable.

**Comment by gforcada** [comment]
There is already one: https://github.com/plone/ploneorg.core/blob/master/ploneorg/core/profiles/default/types/homepage.xml

You can add the fields you need here: https://github.com/plone/ploneorg.core/blob/master/ploneorg/core/content/homepage.py

**Comment by sneridagh** [comment]
@allcaps, @3dogMcNeill please let us know how many fields do you need for the homepage. Can we assume we would edit any "box" in there?

**Comment by allcaps** [comment]
I did this. https://github.com/plone/ploneorg.core/tree/allcaps-homepage

Like someone to review. There ares some issues with the diazo rules. The theme uses the whole width of the page. The default Plone diazo rules assumes the 3 column layout. So this still needs some work. Thats why I delayed the PR.

**Comment by allcaps** [comment]
Openend various issues that cover what needs to be done on #101
